In [ ]:
from fontTools.subset import subset
from pymovements.stimulus import ImageStimulus

import kaamba

In [ ]:
kaamba.scripts.train_on_the_fly("C:/Users/saphi/PycharmProjects/thesis/kaamba_repo/src/kaamba/kaamba_dataset/stimuli/Goettingen/metadata_Goettingen.parquet")

In [1]:
import pymovements as pm
pm.DatasetLibrary.names()

['BSC',
 'BSCII',
 'ChineseReading',
 'CoLAGaze',
 'CodeComprehension',
 'CopCo',
 'DAEMONS',
 'DIDEC',
 'EMTeC',
 'ETDD70',
 'FakeNewsPerception',
 'GGTG',
 'Gaze4Hate',
 'GazeBase',
 'GazeBaseVR',
 'GazeGraph',
 'GazeOnFaces',
 'HBN',
 'IITB_HGC',
 'InteRead',
 'JuDo1000',
 'MECOL1W1',
 'MECOL1W2',
 'MECOL2W1',
 'MECOL2W2',
 'MouseCursor',
 'OneStop',
 'PoTeC',
 'PotsdamBingeRemotePVT',
 'PotsdamBingeWearablePVT',
 'Provo',
 'RaCCooNS',
 'SBSAT',
 'TECO',
 'ToyDataset',
 'ToyDatasetEyeLink',
 'UCL']

In [2]:
dataset = "GazeBase"
dataset_paths = pm.DatasetPaths(root='data/')
pm_dataset = pm.Dataset(dataset, path=dataset_paths)

In [4]:
#pm_dataset.download()
#pm_dataset.extract(verbose = 2)
pm_dataset.scan()

In [15]:
import polars as pl
filepath =pm_dataset.fileinfo['ImageStimulus'].filter(pl.col("stimulus") == "blackout-zero.text.0")
filepath

shape: (1, 2)
┌──────────────────────┬──────────────────────────┐
│ stimulus             ┆ filepath                 │
│ ---                  ┆ ---                      │
│ str                  ┆ str                      │
╞══════════════════════╪══════════════════════════╡
│ blackout-zero.text.0 ┆ blackout-zero.text.0.png │
└──────────────────────┴──────────────────────────┘

In [5]:
pm_dataset.stimuli[0]

IndexError: list index out of range

In [6]:
pm_dataset.paths.stimuli

WindowsPath('data/GGTG/stimuli')

In [7]:
pm_dataset.load(subset={"subject_id": [288], "task_name": ["TEX"]})

Loading gaze files:   0%|          | 0/18 [00:00<?, ?file/s]

C:\Users\saphi\PycharmProjects\thesis\.venv\lib\site-packages\pymovements\dataset\dataset.py:469: ExperimentalWarning: Stimulus support is experimental. Names and behavior may change without being considered a breaking change. Please set the used pymovements version explicitly to prevent unexptected changes. The used pymovements version is v0.26.0+post27.99863d0b.dirty.
  warn(

In [ ]:
import pathlib
import polars as pl
stim = pathlib.Path("C:/Users/saphi/PycharmProjects/thesis/data/GGTG/stimuli")
pl.DataFrame(list(stim.iterdir())).("stimuli.csv")

In [ ]:
gaze = pm_dataset.gaze[0]
gaze.metadata["subject_id"]

In [ ]:
import polars as pl
gazeframes = pl.concat([gaze.samples.with_columns(pl.lit(gaze.metadata["subject_id"]).alias("subject_id"))for gaze in pm_dataset.gaze])

In [ ]:
gaze.samples = gaze.samples.with_columns(pl.lit(gaze.metadata["subject_id"]).alias("subject_id"))

In [ ]:
stimuli = pl.DataFrame(pm_dataset.stimuli)

In [ ]:
grouped = gazeframes.group_by(['subject_id', 'stimulus'])