In [ ]:
from fontTools.subset import subset
from pymovements.stimulus import ImageStimulus

import kaamba

In [ ]:
kaamba.scripts.train_on_the_fly("C:/Users/saphi/PycharmProjects/thesis/kaamba_repo/src/kaamba/kaamba_dataset/stimuli/Goettingen/metadata_Goettingen.parquet")

In [4]:
import pymovements as pm

In [5]:
dataset = "mcfw_gaze"
dataset_paths = pm.DatasetPaths(root='data/')
pm_dataset = pm.Dataset(dataset, path=dataset_paths)

In [6]:
#pm_dataset.download()
#pm_dataset.extract(verbose = 2)
pm_dataset.scan()

In [7]:
pm_dataset.fileinfo["ImageStimulus"]

shape: (80, 2)
┌──────────┬────────────────────────┐
│ image_id ┆ filepath               │
│ ---      ┆ ---                    │
│ str      ┆ str                    │
╞══════════╪════════════════════════╡
│ 20       ┆ dataset\stimuli\20.jpg │
│ 21       ┆ dataset\stimuli\21.jpg │
│ 22       ┆ dataset\stimuli\22.jpg │
│ 23       ┆ dataset\stimuli\23.jpg │
│ 24       ┆ dataset\stimuli\24.jpg │
│ …        ┆ …                      │
│ 95       ┆ dataset\stimuli\95.jpg │
│ 96       ┆ dataset\stimuli\96.jpg │
│ 97       ┆ dataset\stimuli\97.jpg │
│ 98       ┆ dataset\stimuli\98.jpg │
│ 99       ┆ dataset\stimuli\99.jpg │
└──────────┴────────────────────────┘

In [ ]:
import polars as pl
filepath =pm_dataset.fileinfo['ImageStimulus'].filter(pl.col("stimulus") == "blackout-zero.text.0")
filepath

In [ ]:
pm_dataset.stimuli

In [ ]:
url = 'https://github.com/pymovements/pymovements-toy-dataset/archive/refs/heads/main.zip'

dataset_definition = pm.DatasetDefinition(
    name='MyDataset',
    resources=[
        pm.ResourceDefinition(
            content='gaze',
            url=url,
            filename='pymovements-toy-dataset.zip',
            md5='256901852c1c07581d375eef705855d6',
            filename_pattern=r'trial_{text_id:d}_{page_id:d}.csv',
            filename_pattern_schema_overrides={
                'text_id': int, 'page_id': int,
            },
            load_kwargs={
                'read_csv_kwargs': {'separator': '\t'},
                'time_column': 'timestamp',
                'time_unit': 'ms',
                'pixel_columns': ['x', 'y'],
            },
        ),
    ],
    experiment=experiment,
)

In [ ]:

experiment = pm.Experiment(
    sampling_rate=250,
    screen=pm.Screen(
        width_px=1920,
        height_px=1080,
        distance_cm=60,
        origin='upper left',
    ),
)

dataset_definition = pm.DatasetDefinition(
    name='MyDataset',
    experiment=experiment,
    resources=[
        pm.ResourceDefinition(
            content='gaze',
            filename_pattern=r'trial_{text_id:d}_{page_id:d}.csv',
            filename_pattern_schema_overrides={
                'text_id': int, 'page_id': int,
            },
            load_kwargs={
                'read_csv_kwargs': {'separator': '\t'},
                'time_column': 'timestamp',
                'time_unit': 'ms',
                'pixel_columns': ['x', 'y'],
            },
        ),
    ],
)

In [4]:
pm_dataset.paths.stimuli

WindowsPath('data/mcfw-gaze/stimuli')

In [5]:
x = pm_dataset.load(subset={"subject_id": ["001"]})

Loading gaze files:   0%|          | 0/313 [00:00<?, ?file/s]

C:\Users\saphi\PycharmProjects\thesis\.venv\lib\site-packages\pymovements\dataset\dataset.py:469: ExperimentalWarning: Stimulus support is experimental. Names and behavior may change without being considered a breaking change. Please set the used pymovements version explicitly to prevent unexptected changes. The used pymovements version is v0.26.2+post10.2b5a78f6.dirty.
  warn(

In [6]:
x.gaze[0].metadata

{'subject_id': '001', 'stimulus': 'gaze_pattern_auth_trial', 'trial_id': '1'}

In [ ]:
import pathlib
import polars as pl
stim = pathlib.Path("C:/Users/saphi/PycharmProjects/thesis/data/GGTG/stimuli")
pl.DataFrame(list(stim.iterdir())).("stimuli.csv")

In [ ]:
gaze = pm_dataset.gaze[0]
gaze.metadata["subject_id"]

In [ ]:
import polars as pl
gazeframes = pl.concat([gaze.samples.with_columns(pl.lit(gaze.metadata["subject_id"]).alias("subject_id"))for gaze in pm_dataset.gaze])

In [ ]:
gaze.samples = gaze.samples.with_columns(pl.lit(gaze.metadata["subject_id"]).alias("subject_id"))

In [ ]:
stimuli = pl.DataFrame(pm_dataset.stimuli)

In [ ]:
grouped = gazeframes.group_by(['subject_id', 'stimulus'])